export const AMOUNT_PROPOSAL_GALLERY_IMAGES = 60;
export const PROPOSAL_GALLERY_IMAGE_SIZE = 96;
export const PROPOSAL_GALLERY_MARGIN_SIZE = 2;
export const PROPOSAL_MAIN_IMAGE_SIZE = 320;
export const DROPOSAL_IMAGE_SIZE = 320;
